### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sindresorhus** [paulcbetts/electron-compile#8]
Some quick feedback:

> Unfortunately, the very first file that you set up app.ready in must be written in ES5. Of course, you can always make this file as small as possible, or just require in a real file once you call init().

This is kind of a bummer... Are there any changes that could be done in Electron itself to make this possible?

> app.on('ready', function() {
  require('electron-compile').init();
});

Why must it be inside the ready call? I would think it would be beneficial to run it as soon as possible. Does it really require the app to be ready?

**Comment by paulcbetts** [comment]
> This is kind of a bummer... Are there any changes that could be done in Electron itself to make this possible?

Maybe? It definitely requires _some_ change to Electron, I'll have to think about that.

> Why must it be inside the ready call? I would think it would be beneficial to run it as soon as possible. Does it really require the app to be ready?

At the moment, we need to do it because we can only set up the protocol hook once app is ready. 

So, one thing we could do is, instead of immediately setting up the hook in `init`, we could actually just set an `.on('ready')` listener in init, but the problem is that `ready` isn't a replaying event like `document.ready` is - if you add a listener after we're already ready, that listener is never called, and we have no way to know if we're ready or not. We should fix this in Electron basically.

**Comment by jcblw** [comment]
If electron has the ability to preload modules like iojs, it would be possible to hook into the require statement before the first file is ran. Allowing every file to be coffee/es6. 

I know with iojs it works like this.

```shell
iojs -r babel/register entry.js
```

**Comment by paulcbetts** [comment]
I think we've got as close as we can without doing some Extreme Makeovers to Electron. Thanks for the tip!
